### ISSUE TITLE
small mistake in readme

### ISSUE THREAD

**Issue by devlocalhost** [gicrisf/swapforqute#2]
`git clone --depth 1 https://github.com/gicrisf/swapforqute ~/.config/qutebrowser/userscripts` should be `git clone --depth 1 https://github.com/gicrisf/swapforqute ~/.config/qutebrowser/userscripts/swapforqute`, otherwise: `chmod: cannot access '/home/dev64/.config/qutebrowser/userscripts/swapforqute/main.py': No such file or directory`

**Comment by gicrisf** [comment]
Thank you for reporting it to me! You're right, otherwise the files in the repo would be dumped directly in the userscript directory

**Comment by gicrisf** [comment]
Solved with #7416bfe

thanks again
